FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:18-alpine AS runner

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production
RUN npm install typeorm reflect-metadata pg

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/app.js"] 